### ISSUE TITLE
About Aligner-50K, Aligner-2B and Aligner-13B

### ISSUE THREAD

**Issue by liudan193** [Aligner2024/aligner#8]
Hi, I am wondering if there are any plans to open-source Aligner-50K, as well as the parameters for other model sizes. If so, do you have an estimated release date for when that might happen?

**Comment by cby-pku** [comment]
Hi, @liudan193,
Thank you for your interest in the Aligner project! We are thrilled to see Aligner gaining widespread adoption.

In February of this year, we open-sourced a subset of the Aligner training dataset on Hugging Face — a 20K dataset focused on safety-related prompts. Since then, increasingly powerful models like GPT-4o have emerged, enabling the construction of higher-quality correction datasets. 

To further advance research on the correction paradigm and the Aligner method, we plan to open-source additional correction datasets beyond the Aligner-50K by **the end of December.** These datasets will cover a broader range of tasks, such as **math**, **summarization**, and **general reasoning**, and will feature higher-quality answers and corrections.

Additionally, we will release more Aligner models for community use. We hope these contributions will empower the community to explore and advance correction paradigms grounded in the Aligner approach.

**Comment by liudan193** [comment]
Thanks for your reply!
